<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="author" content="ANAND PANDEY" />
<meta http-equiv="contact" content="anandp219@gmail.com" />
<title>
Sipp-url shortener
</title>
<link href="style.css" rel="stylesheet" type="text/css"/>
<link rel="icon" href="http://aiz.free.fr/ED/ED_icon_green_V5.ico" type="image/x-icon"/>
<link rel="shortcut icon" http://aiz.free.fr/ED/ED_icon_green_V5.icostart=150" type="image/x-icon" />
</head>
<body>